In [1]:
import random

import torch

import utils.data as data
import utils.evo_data as evo_data
import utils.params as params
import utils.objectives as objectives
from utils.baseline import get_baseline
from utils.backbone import get_backbone

from train_backbone import train_backbone
from test_backbone import test_backbone
from finetune_backbone import finetune
from train_head import train_head
from test_head import test_head

In [2]:
random.seed(params.SEED)

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\nUsing device: {device}")


Using device: cuda


In [4]:
dataset, num_features = data.prepare_data()
train_dataset, val_dataset, test_dataset = data.get_datasets(dataset)
train_loader, val_loader, test_loader = data.get_dataloaders(train_dataset, val_dataset, test_dataset)

In [5]:
train_backbone(get_baseline, num_features, train_loader, val_loader, device, params.BL_BEST_MODEL_PATH, params.LAST_MODEL_PATH)


Epoch 1/25:
Training Loss: 0.9955
Validation Loss: 0.9378

Epoch 2/25:
Training Loss: 1.0046
Validation Loss: 0.9368

Epoch 3/25:
Training Loss: 0.9997
Validation Loss: 0.9403

Epoch 4/25:
Training Loss: 0.9983
Validation Loss: 0.9371

Epoch 5/25:
Training Loss: 1.0066
Validation Loss: 0.9351

Epoch 6/25:
Training Loss: 1.0008
Validation Loss: 0.9384

Epoch 7/25:
Training Loss: 1.0068
Validation Loss: 0.9374

Epoch 8/25:
Training Loss: 1.0004
Validation Loss: 0.9378

Epoch 9/25:
Training Loss: 0.9955
Validation Loss: 0.9358

Epoch 10/25:
Training Loss: 1.0184
Validation Loss: 0.9393

Epoch 11/25:
Training Loss: 1.0164
Validation Loss: 0.9403

Epoch 12/25:
Training Loss: 0.9989
Validation Loss: 0.9353

Epoch 13/25:
Training Loss: 0.9954
Validation Loss: 0.9359

Epoch 14/25:
Training Loss: 1.0164
Validation Loss: 0.9358

Epoch 15/25:
Training Loss: 0.9996
Validation Loss: 0.9370

Epoch 16/25:
Training Loss: 0.9960
Validation Loss: 0.9356

Epoch 17/25:
Training Loss: 1.0055
Validation Lo

In [6]:
test_backbone(num_features, test_dataset, test_loader, device, params.BL_BEST_MODEL_PATH, get_baseline, params.PLOT_BASELINE)

Test Loss: 0.8839
Zero Change Benchmark MSE Loss: 0.9679
Previous Day Change Benchmark MSE Loss: 1.8054
Mean Benchmark MSE Loss: 0.9679


([array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dtype=float32),
  array([-0.00763938], dt

In [7]:
train_backbone(get_backbone, num_features, train_loader, val_loader, device, params.BEST_MODEL_PATH, params.LAST_MODEL_PATH)


Epoch 1/25:
Training Loss: 1.3216
Validation Loss: 0.9394

Epoch 2/25:
Training Loss: 1.2038
Validation Loss: 1.0245

Epoch 3/25:
Training Loss: 1.1271
Validation Loss: 1.1509

Epoch 4/25:
Training Loss: 1.1091
Validation Loss: 3.0140

Epoch 5/25:
Training Loss: 1.1045
Validation Loss: 1.2359

Epoch 6/25:
Training Loss: 1.0708
Validation Loss: 0.9357

Epoch 7/25:
Training Loss: 1.0469
Validation Loss: 0.9695

Epoch 8/25:
Training Loss: 1.0457
Validation Loss: 2.8694

Epoch 9/25:
Training Loss: 1.0361
Validation Loss: 0.9380

Epoch 10/25:
Training Loss: 1.0389
Validation Loss: 0.9366

Epoch 11/25:
Training Loss: 1.0366
Validation Loss: 1.1128

Epoch 12/25:
Training Loss: 1.0193
Validation Loss: 0.9522

Epoch 13/25:
Training Loss: 1.0455
Validation Loss: 0.9749

Epoch 14/25:
Training Loss: 1.0242
Validation Loss: 0.9355

Epoch 15/25:
Training Loss: 1.0195
Validation Loss: 0.9338

Epoch 16/25:
Training Loss: 1.0211
Validation Loss: 0.9414

Epoch 17/25:
Training Loss: 1.0214
Validation Lo

In [8]:
test_backbone(num_features, test_dataset, test_loader, device, params.BEST_MODEL_PATH, get_backbone, params.PLOT_BACKBONE)

Test Loss: 0.8832
Zero Change Benchmark MSE Loss: 0.9679
Previous Day Change Benchmark MSE Loss: 1.8054
Mean Benchmark MSE Loss: 0.9679


([array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dt

In [9]:
test_backbone(num_features, test_dataset, test_loader, device, params.BEST_MODEL_PATH, get_backbone, f"last_{params.PLOT_BACKBONE}")

Test Loss: 0.8832
Zero Change Benchmark MSE Loss: 0.9679
Previous Day Change Benchmark MSE Loss: 1.8054
Mean Benchmark MSE Loss: 0.9679


([array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dtype=float32),
  array([-0.02242802], dt

In [10]:
finetune(device, params.BL_BEST_MODEL_PATH, get_baseline, params.FT_NUM_EPOCHS, params.FT_BL_BEST_MODEL_PATH, params.FT_BL_LAST_MODEL_PATH, params.FT_PLOT_BASELINE)


Epoch 1/25:
Training Loss: 1.0965
Validation Loss: 0.8637

Epoch 2/25:
Training Loss: 1.0914
Validation Loss: 0.8625

Epoch 3/25:
Training Loss: 1.0992
Validation Loss: 0.8665

Epoch 4/25:
Training Loss: 1.0904
Validation Loss: 0.8621

Epoch 5/25:
Training Loss: 1.0833
Validation Loss: 0.8659

Epoch 6/25:
Training Loss: 1.0896
Validation Loss: 0.8632

Epoch 7/25:
Training Loss: 1.0897
Validation Loss: 0.8659

Epoch 8/25:
Training Loss: 1.0881
Validation Loss: 0.8631

Epoch 9/25:
Training Loss: 1.1077
Validation Loss: 0.8645

Epoch 10/25:
Training Loss: 1.0841
Validation Loss: 0.8669

Epoch 11/25:
Training Loss: 1.0852
Validation Loss: 0.8640

Epoch 12/25:
Training Loss: 1.0859
Validation Loss: 0.8641

Epoch 13/25:
Training Loss: 1.0917
Validation Loss: 0.8657

Epoch 14/25:
Training Loss: 1.0818
Validation Loss: 0.8624

Epoch 15/25:
Training Loss: 1.0948
Validation Loss: 0.8646

Epoch 16/25:
Training Loss: 1.1131
Validation Loss: 0.8637

Epoch 17/25:
Training Loss: 1.0859
Validation Lo

([array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.00726414], dtype=float32),
  array([0.0

In [11]:
finetune(device, params.BEST_MODEL_PATH, get_backbone, params.FT_NUM_EPOCHS, params.FT_BEST_MODEL_PATH, params.FT_LAST_MODEL_PATH, params.FT_PLOT_BACKBONE)


Epoch 1/25:
Training Loss: 1.1241
Validation Loss: 0.8555

Epoch 2/25:
Training Loss: 1.1156
Validation Loss: 0.9159

Epoch 3/25:
Training Loss: 1.0992
Validation Loss: 0.9109

Epoch 4/25:
Training Loss: 1.1040
Validation Loss: 0.8559

Epoch 5/25:
Training Loss: 1.0930
Validation Loss: 0.8859

Epoch 6/25:
Training Loss: 1.1026
Validation Loss: 0.8659

Epoch 7/25:
Training Loss: 1.0948
Validation Loss: 0.8600

Epoch 8/25:
Training Loss: 1.1153
Validation Loss: 0.8628

Epoch 9/25:
Training Loss: 1.1010
Validation Loss: 0.8548

Epoch 10/25:
Training Loss: 1.1035
Validation Loss: 0.8901

Epoch 11/25:
Training Loss: 1.1084
Validation Loss: 0.8600

Epoch 12/25:
Training Loss: 1.1079
Validation Loss: 0.8549

Epoch 13/25:
Training Loss: 1.1071
Validation Loss: 0.8861

Epoch 14/25:
Training Loss: 1.0918
Validation Loss: 0.8659

Epoch 15/25:
Training Loss: 1.1017
Validation Loss: 0.8623

Epoch 16/25:
Training Loss: 1.1007
Validation Loss: 0.8576

Epoch 17/25:
Training Loss: 1.1127
Validation Lo

([array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.00631425], dtype=float32),
  array([0.0

In [12]:
in_train, p_train = evo_data.get_train_data(device, model=params.BEST_MODEL_PATH, target=params.TARGET)

In [13]:
train_head(in_train, p_train, device, objective=objectives.cumulative_return, best_model_path=params.BEST_CR_GENOME_PATH, last_model_path=params.LAST_CR_GENOME_PATH, plt_path=params.CR_PLOTS)

Starting training
Epoch 1 / 25
Max episode return:  1872.1033935546875
Max episode reward:  -0.012994537129998207
Episode Duration: 570.19
Epoch 2 / 25
Max episode return:  1564.40771484375
Max episode reward:  0.022443968802690506
Episode Duration: 583.05
Epoch 3 / 25
Max episode return:  1604.265869140625
Max episode reward:  0.08280802518129349
Episode Duration: 588.22
Epoch 4 / 25
Max episode return:  2058.053955078125
Max episode reward:  0.042637899518013
Episode Duration: 579.35
Epoch 5 / 25
Max episode return:  2062.98974609375
Max episode reward:  -0.012498868629336357
Episode Duration: 571.29
Epoch 6 / 25
Max episode return:  1948.8404541015625
Max episode reward:  0.0795581042766571
Episode Duration: 584.10
Epoch 7 / 25
Max episode return:  2031.1112060546875
Max episode reward:  -0.019546985626220703
Episode Duration: 578.55
Epoch 8 / 25
Max episode return:  2186.7490234375
Max episode reward:  0.06766635924577713
Episode Duration: 577.38
Epoch 9 / 25
Max episode return:  1

In [14]:
train_head(in_train, p_train, device, objective=objectives.sharpe_ratio, best_model_path=params.BEST_SR_GENOME_PATH, last_model_path=params.LAST_SR_GENOME_PATH, plt_path=params.SR_PLOTS)

Starting training
Epoch 1 / 25
Max episode return:  1979.35009765625
Max episode reward:  -0.23562268912792206
Episode Duration: 621.22
Epoch 2 / 25
Max episode return:  1773.26318359375
Max episode reward:  0.06442423164844513
Episode Duration: 610.18
Epoch 3 / 25
Max episode return:  2018.40234375
Max episode reward:  0.039188701659440994
Episode Duration: 613.46
Epoch 4 / 25
Max episode return:  1986.9534912109375
Max episode reward:  0.02919020690023899
Episode Duration: 643.04
Epoch 5 / 25
Max episode return:  2037.865234375
Max episode reward:  -0.24375799298286438
Episode Duration: 612.74
Epoch 6 / 25
Max episode return:  1567.79638671875
Max episode reward:  -0.02316075935959816
Episode Duration: 501.21
Epoch 7 / 25
Max episode return:  1523.2255859375
Max episode reward:  0.2741525173187256
Episode Duration: 502.05
Epoch 8 / 25
Max episode return:  2036.865234375
Max episode reward:  -0.21786613762378693
Episode Duration: 497.69
Epoch 9 / 25
Max episode return:  1622.487548828

In [15]:
train_head(in_train, p_train, device, objective=objectives.maximum_drawdown, best_model_path=params.BEST_MD_GENOME_PATH, last_model_path=params.LAST_MD_GENOME_PATH, plt_path=params.MD_PLOTS)

Starting training
Epoch 1 / 25
Max episode return:  2028.484375
Max episode reward:  0.938112199306488
Episode Duration: 643.08
Epoch 2 / 25
Max episode return:  1865.1866455078125
Max episode reward:  0.9717128276824951
Episode Duration: 662.31
Epoch 3 / 25
Max episode return:  1902.3822021484375
Max episode reward:  0.9724088311195374
Episode Duration: 674.07
Epoch 4 / 25
Max episode return:  2117.183837890625
Max episode reward:  0.9863355755805969
Episode Duration: 579.18
Epoch 5 / 25
Max episode return:  1482.9739990234375
Max episode reward:  0.9726976156234741
Episode Duration: 597.47
Epoch 6 / 25
Max episode return:  2176.4892578125
Max episode reward:  0.9675266742706299
Episode Duration: 653.41
Epoch 7 / 25
Max episode return:  1344.09130859375
Max episode reward:  0.9594245553016663
Episode Duration: 674.53
Epoch 8 / 25
Max episode return:  1975.9102783203125
Max episode reward:  0.9845733046531677
Episode Duration: 665.85
Epoch 9 / 25
Max episode return:  1803.63037109375
M